### Scrape list of cities/URLs from 'All Cities' page (BeautifulSoup)

In [1]:
import numpy as np
import pandas as pd

from bs4 import BeautifulSoup
import requests
import time, os

In [2]:
# Get complete list of cities from single page

url = 'https://www.expatistan.com/cost-of-living/all-cities' 

response = requests.get(url)
response.status_code  # 2** = successful read

200

In [3]:
page = response.text
soup = BeautifulSoup(page, "lxml")
# print(soup.prettify())

In [4]:
# Returns lists of cities/urls only


list_name = []
list_url = []

for entry in soup.find_all('div', id='all-cities'):        # entire table
    for city in entry.find_all('li'):                      # only cities
        for link in city.find_all('a'):                    # grab links
            list_name.append(link.text)
            list_url.append(link.get('href'))

# list_name
# list_url

In [5]:
# Get corresponding list of countries

current_country = ''
list_country = []

for entry in soup.find_all('div', id='all-cities'):         # entire table
     for link in entry.find_all('a'):                       # grab links
            url = link.get('href')
            name = link.text
            
            if '/country/' in url:                          # common feature to country URLs
                current_country = name                      # update 'Country' label
                pass                                        # not new entry
            else:
                list_country.append(current_country)        # if URL not country, it's a city to label

# list_country

In [6]:
# Create dataframe from three lists

list_tuples1 = list(zip(list_name, list_country, list_url))
df1 = pd.DataFrame(list_tuples1, columns = ['City', 'Country', 'URL'])

In [7]:
# Remove cities lacking any user-contributed data

df1 = df1[~df1["URL"].str.contains('/rate/')]          # cities with /rate/ in URL are placeholders without contributions
df1.reset_index(drop=True, inplace=True)             

# 2,475 eligible cities (Afghanistan>Kabul ... Zimbabwe>Zvishavane District) 

df1

,City,Country,URL
0,Kabul,Afghanistan,https://www.expatistan.com/cost-of-living/kabul
1,Mariehamn,Aland Islands,https://www.expatistan.com/cost-of-living/mari...
2,Durrës,Albania,https://www.expatistan.com/cost-of-living/durres
3,Elbasan,Albania,https://www.expatistan.com/cost-of-living/elbasan
4,Korçë,Albania,https://www.expatistan.com/cost-of-living/korce
...,...,...,...
2470,Kadoma,Zimbabwe,https://www.expatistan.com/cost-of-living/kadoma
2471,Marondera,Zimbabwe,https://www.expatistan.com/cost-of-living/maro...
2472,Masvingo,Zimbabwe,https://www.expatistan.com/cost-of-living/masv...
2473,Mutare,Zimbabwe,https://www.expatistan.com/cost-of-living/mutare
2474,Zvishavane District,Zimbabwe,https://www.expatistan.com/cost-of-living/zvis...

### Collect target (cost of living), feature, and contribution info from each city page

In [70]:
# For cleaning cost-of-living string

def COL_to_float(string):
    
    str_list = string.split(" ")
    cost_raw = str_list[0]
    cost_str = cost_raw.replace('$', '').replace(',', '')
    cost = float(cost_str)
    
    return cost

In [71]:
# Instantiate empty list for each variable

rent_85m2_expens = []
rent_85m2_normal = []
rent_45m2_expens = []
rent_45m2_normal = []
eatout_lunch = []
eatout_dinner = []
taxi_5mi = []
gas_liter = []
pubtrans_monthly = []
internet_monthly = []
TV_40in = []
cappuccino = []
mobile_wifi_128gb = []

list_COL_fam4 = []
list_COL_sin1 = []

list_n_prices = []
list_n_people = []

In [72]:
# Lists of features for looping

list_feature_texts = ['Monthly rent for 85 m2 (900 sqft) furnished accommodation in expensive area',
                 'Monthly rent for 85 m2 (900 sqft) furnished accommodation in normal area',
                 'Monthly rent for a 45 m2 (480 sqft) furnished studio in expensive area',
                 'Monthly rent for a 45 m2 (480 sqft) furnished studio in normal area',
                 'Basic lunchtime menu (including a drink) in the business district',
                 'Basic dinner out for two in neighborhood pub',
                 'Taxi trip on a business day, basic tariff, 8 km. (5 miles)',
                 '1 liter (1/4 gallon) of gas',
                 'Monthly ticket public transport',
                 'Internet 8 mbps (1 month)',
                 '40” flat screen tv',                     # special quotation mark! (”)
                 'Cappuccino in expat area of the city',
                 'Ipad wi-fi 128gb']

list_feature_names = ['rent_85m2_expens',
                      'rent_85m2_normal',
                      'rent_45m2_expens',
                      'rent_45m2_normal',
                      'eatout_lunch',
                      'eatout_dinner',
                      'taxi_5mi',
                      'gas_liter',
                      'pubtrans_monthly',
                      'internet_monthly',
                      'TV_40in',
                      'cappuccino',
                      'mobile_wifi_128gb']


list_of_lists = [rent_85m2_expens,
                      rent_85m2_normal,
                      rent_45m2_expens,
                      rent_45m2_normal,
                      eatout_lunch,
                      eatout_dinner,
                      taxi_5mi,
                      gas_liter,
                      pubtrans_monthly,
                      internet_monthly,
                      TV_40in,
                      cappuccino,
                      mobile_wifi_128gb]

list_of_urls = list(df1["URL"])

In [73]:
# Scraping tool...be sure lists in cell above are empty!

import random
from fake_useragent import UserAgent

for url in list_of_urls[1781:]:  # from Al Mubarraz, Saudi Arabia
    
    new_url = url + '?currency=USD'  # generate page version with USD
    
    ua = UserAgent()
    user_agent = {'User-agent': ua.random}                       # new user_agent every iteration
    response = requests.get(new_url, headers = user_agent)                       
    page = response.text
    soup_usd = BeautifulSoup(page, "lxml")
    
    # 1. Get price features
    
    for i, feature in enumerate(list_feature_texts):
        
        chunk1 = soup_usd.find('a', text=feature)
        check = chunk1.findNext().findNext()            
        
        if check.name == 'tr':    # 'tr' if country uses USD only
            feature_value = chunk1.findNext().text[2:-2]
        else:                     # 'li' if USD is not only currency
            feature_value = chunk1.findNext().findNext().text[2:-2]

        if feature_value[0] != '$':  # no data for feature
           feature_value = np.nan
        else:
            fv_str = feature_value.replace('$', '').replace(',', '')
            feature_value = float(fv_str)
        
        list_of_lists[i].append(feature_value)
    
    # 2. Get cost of living estimates
    
    if soup_usd.find_all('div', class_='cost-of-living-summary centered right-widget'):    # Summary window must be present
        chunk2 = soup_usd.find('div', class_='cost-of-living-summary centered right-widget')
        COL_fam4_raw = chunk2.find_all('span', class_='price')[0].text
        COL_fam4 = COL_to_float(COL_fam4_raw)
        COL_sin1_raw = chunk2.find_all('span', class_='price')[1].text
        COL_sin1 = COL_to_float(COL_sin1_raw)
    else:
        COL_fam4, COL_sin1 = np.nan, np.nan
    
    list_COL_sin1.append(COL_sin1)
    list_COL_fam4.append(COL_fam4)
    
    # 3. Get contribution info
    
    chunk3 = soup_usd.find_all('div', class_='accuracy-report')[-1].text       # evaluation always last on page
    sentences = chunk3.split('.')                                              # split into sentences
    sentence_raw = sentences[2].strip()                                        # select 3rd sentence in accuracy-report
    sentence = sentence_raw.replace('less than ', '-')                         # flag cities with scarce data as negative for now
    words = sentence.split(' ')
    # no_prices, no_people = words[4], words[8]
    no_prices, no_people = int(words[4].replace(',', '')), int(words[8].replace(',', '')) 
    
    list_n_prices.append(no_prices)                               
    list_n_people.append(no_people)
    
    # 4. Pause like a human
    
    wait = .5 + 10 * random.random()
    time.sleep(wait)
    print(f'{url[41:]}, {no_prices}, ${COL_sin1}, waited {wait:0.4} sec.')

/al-mubarraz, -10, $1514.0, waited 2.391 sec.
/al-qurayyat, -10, $nan, waited 2.861 sec.
/arar, -10, $920.0, waited 7.16 sec.
/buraidah, 12, $933.0, waited 5.214 sec.
/dammam, 74, $1218.0, waited 5.32 sec.
/jeddah, 126, $1062.0, waited 7.589 sec.
/jizan, -10, $1212.0, waited 8.114 sec.
/jubail, -10, $1275.0, waited 5.163 sec.
/khamis-mushait, -10, $862.0, waited 9.105 sec.
/mecca, -10, $1181.0, waited 4.197 sec.
/medina, 22, $1243.0, waited 7.489 sec.
/najran, -10, $nan, waited 6.287 sec.
/riyadh, 270, $1741.0, waited 9.969 sec.
/sakaka, -10, $739.0, waited 5.726 sec.
/at-ta-if, -10, $nan, waited 1.71 sec.
/tabuk, -10, $1064.0, waited 6.955 sec.
/yanbu-al-bahr, -10, $nan, waited 8.462 sec.
/dakar, 43, $1964.0, waited 1.007 sec.
/grand-dakar, -10, $nan, waited 4.803 sec.
/kolda, -10, $nan, waited 2.787 sec.
/saint-louis, -10, $nan, waited 9.573 sec.
/ziguinchor, -10, $nan, waited 5.599 sec.
/belgrade, 261, $1168.0, waited 8.485 sec.
/kraljevo, -10, $896.0, waited 6.518 sec.
/krusevac, 37, $556.0, waited 5.06 sec.
/nis, 26, $608.0, waited 9.882 sec.
/novi-pazar, -10, $nan, waited 2.358 sec.
/novi-sad, 87, $832.0, waited 1.441 sec.
/subotica, -10, $556.0, waited 6.23 sec.
/uzice, -10, $1638.0, waited 9.804 sec.
/valjevo, -10, $1172.0, waited 1.243 sec.
/zrenjanin, -10, $643.0, waited 9.56 sec.
/victoria-seychelles, 89, $2407.0, waited 3.02 sec.
/bo, -10, $nan, waited 6.421 sec.
/freetown, 15, $1252.0, waited 8.065 sec.
/kenema, -10, $nan, waited 9.284 sec.
/singapore, 421, $3619.0, waited 1.704 sec.
/bratislava, 130, $1456.0, waited 0.5673 sec.
/poprad, -10, $1107.0, waited 4.63 sec.
/presov, 16, $1111.0, waited 0.569 sec.
/prievidza, 19, $1203.0, waited 2.611 sec.
/trencin, -10, $1049.0, waited 6.225 sec.
/trnava, -10, $1134.0, waited 8.597 sec.
/zilina, -10, $1029.0, waited 4.993 sec.
/ljubljana, 188, $1768.0, waited 10.2 sec.
/maribor, 31, $1067.0, waited 6.462 sec.
/honiara, -10, $2163.0, waited 7.667 sec.
/bosaso, -10, $nan, waited 5.143 sec.
/hargeysa, -10, $nan, waited 0.6797 sec.
/mogadishu, -10, $11081.0, waited 1.748 sec.
/benoni, -10, $985.0, waited 2.568 sec.
/bethal, -10, $nan, waited 1.839 sec.
/bhisho, -10, $1194.0, waited 1.692 sec.
/bloemfontein, -10, $777.0, waited 6.513 sec.
/boksburg, -10, $1408.0, waited 3.483 sec.
/botshabelo, -10, $nan, waited 5.521 sec.
/cape-town, 275, $1524.0, waited 4.387 sec.
/carletonville, -10, $1192.0, waited 5.801 sec.
/durban, 123, $1234.0, waited 3.489 sec.
/george, -10, $820.0, waited 7.962 sec.
/johannesburg, 374, $1330.0, waited 9.433 sec.
/kimberley, -10, $1231.0, waited 3.25 sec.
/kroonstad, -10, $nan, waited 3.623 sec.
/middelburg-mpumalanga-south-africa, -10, $1073.0, waited 8.9 sec.
/nelspruit, -10, $993.0, waited 9.933 sec.
/newcastle-south-africa, -10, $1058.0, waited 8.815 sec.
/noorder-paarl, -10, $1089.0, waited 6.141 sec.
/orkney, -10, $1068.0, waited 2.485 sec.
/phalaborwa, -10, $831.0, waited 9.364 sec.
/pietermaritzburg, -10, $902.0, waited 8.205 sec.
/polokwane, 43, $931.0, waited 5.358 sec.
/port-elizabeth, 31, $1045.0, waited 8.29 sec.
/potchefstroom, -10, $843.0, waited 9.693 sec.
/potgietersrus, -10, $1448.0, waited 8.127 sec.
/pretoria, 229, $1150.0, waited 9.419 sec.
/queenstown, -10, $1114.0, waited 0.9685 sec.
/richards-bay, -10, $915.0, waited 9.753 sec.
/rustenburg, 14, $1020.0, waited 3.278 sec.
/soweto, -10, $1124.0, waited 0.5131 sec.
/tembisa, -10, $1792.0, waited 9.01 sec.
/vereeniging, -10, $1010.0, waited 6.925 sec.
/welkom, 34, $842.0, waited 0.9504 sec.
/witbank, -10, $nan, waited 7.817 sec.
/worcester, -10, $700.0, waited 5.301 sec.
/andong, -10, $nan, waited 7.969 sec.
/ansan, -10, $nan, waited 5.824 sec.
/anyang-south-korea, -10, $2301.0, waited 3.092 sec.
/bucheon, -10, $1640.0, waited 4.941 sec.
/busan, -10, $1420.0, waited 9.559 sec.
/changwon, -10, $2130.0, waited 9.005 sec.
/chuncheon, -10, $nan, waited 3.95 sec.
/chungju, 18, $nan, waited 4.272 sec.
/daegu, -10, $1263.0, waited 7.005 sec.
/daejeon, -10, $1355.0, waited 9.749 sec.
/gangneung, -10, $nan, waited 7.652 sec.
/gunsan, -10, $nan, waited 9.054 sec.
/gwangju, -10, $1299.0, waited 4.299 sec.
/jeju, -10, $1949.0, waited 7.859 sec.
/jeonju, -10, $nan, waited 7.199 sec.
/jinju, -10, $nan, waited 6.829 sec.
/mokpoo, -10, $nan, waited 8.919 sec.
/seongnam, -10, $1504.0, waited 4.703 sec.
/seoul, 283, $2196.0, waited 2.487 sec.
/suwon, -10, $1364.0, waited 1.472 sec.
/uijongbu, -10, $nan, waited 1.653 sec.
/ulsan, -10, $2125.0, waited 8.25 sec.
/wonju, -10, $1203.0, waited 5.478 sec.
/yongin, -10, $nan, waited 10.28 sec.
/yosu, -10, $nan, waited 8.572 sec.
/juba, 32, $900.0, waited 3.657 sec.
/albacete, -10, $1148.0, waited 9.655 sec.
/algeciras, 65, $1124.0, waited 8.354 sec.
/alicante, 232, $1356.0, waited 6.749 sec.
/almeria, 228, $1274.0, waited 8.476 sec.
/almunecar, -10, $1198.0, waited 2.472 sec.
/badajoz, 15, $1081.0, waited 7.336 sec.
/barcelona-spain, 1601, $2147.0, waited 4.898 sec.
/benidorm, 37, $1408.0, waited 5.276 sec.
/bilbao, 253, $1838.0, waited 5.622 sec.
/burgos, 82, $1300.0, waited 2.832 sec.
/caceres, 50, $1106.0, waited 8.341 sec.
/cadiz, 68, $1388.0, waited 4.869 sec.
/cartagena-spain, 107, $1137.0, waited 3.797 sec.
/castellon-de-la-plana, 79, $1088.0, waited 6.408 sec.
/ceuta, -10, $1453.0, waited 8.719 sec.
/cordova, 117, $1344.0, waited 7.728 sec.
/corunna, 260, $1386.0, waited 2.095 sec.
/elx, 30, $1223.0, waited 7.734 sec.
/gijon, 20, $1309.0, waited 5.147 sec.
/granada-spain, 368, $1286.0, waited 0.9927 sec.
/huelva, 100, $1093.0, waited 5.541 sec.
/jaca, 42, $1511.0, waited 3.197 sec.
/jaen, 49, $1058.0, waited 5.613 sec.
/jerez-de-la-frontera, 141, $1138.0, waited 5.939 sec.
/las-palmas-de-gran-canaria, 301, $1465.0, waited 0.6675 sec.
/leon-spain, 13, $1265.0, waited 9.172 sec.
/lleida, 29, $1249.0, waited 7.661 sec.
/logrono, 76, $1197.0, waited 3.208 sec.
/madrid, 1991, $2037.0, waited 1.96 sec.
/malaga, 349, $1540.0, waited 9.77 sec.
/marbella, 89, $1835.0, waited 10.23 sec.
/melilla, -10, $1300.0, waited 5.526 sec.
/murcia, 196, $1378.0, waited 8.672 sec.
/ourense, 192, $1149.0, waited 0.7159 sec.
/oviedo, 43, $1406.0, waited 0.6184 sec.
/palma-de-mallorca, 171, $1918.0, waited 5.97 sec.
/pamplona, 244, $1682.0, waited 8.926 sec.
/salamanca, 154, $1239.0, waited 1.283 sec.
/san-sebastian, 127, $2079.0, waited 3.446 sec.
/santa-cruz-de-tenerife, 391, $1464.0, waited 2.014 sec.
/santander, 26, $1381.0, waited 4.763 sec.
/santiago-de-compostela, 88, $1335.0, waited 7.193 sec.
/segovia, 32, $1319.0, waited 2.555 sec.
/seville, 303, $1450.0, waited 8.204 sec.
/tarragona, 178, $1463.0, waited 4.689 sec.
/toledo-spain, 97, $1171.0, waited 8.816 sec.
/valencia-spain, 389, $1556.0, waited 3.435 sec.
/valladolid, 169, $1433.0, waited 0.9493 sec.
/vigo, 186, $1349.0, waited 8.226 sec.
/vitoria-gasteiz, -10, $1581.0, waited 6.033 sec.
/zaragoza, 220, $1483.0, waited 9.38 sec.
/anuradhapura, -10, $1382.0, waited 6.924 sec.
/colombo, 183, $846.0, waited 10.36 sec.
/galle, -10, $nan, waited 4.184 sec.
/kalmunai, -10, $nan, waited 7.501 sec.
/kandy, 24, $546.0, waited 6.964 sec.
/trincomalee, -10, $nan, waited 1.258 sec.
/valvedditturai, -10, $nan, waited 5.927 sec.
/vavuniya, -10, $nan, waited 7.105 sec.
/ad-duwaym, -10, $38.0, waited 8.706 sec.
/al-fashir, -10, $nan, waited 3.42 sec.
/kassala, -10, $nan, waited 0.7371 sec.
/khartoum, 83, $134.0, waited 2.605 sec.
/malakal, -10, $nan, waited 6.282 sec.
/wad-madani, -10, $48.0, waited 0.9209 sec.
/paramaribo, -10, $294.0, waited 1.848 sec.
/longyearbyen-svalbard-and-jan-mayen, -10, $nan, waited 1.644 sec.
/mbabane, -10, $836.0, waited 7.678 sec.
/boras, -10, $1704.0, waited 10.34 sec.
/gothenburg, 129, $2287.0, waited 0.6101 sec.
/gavle, 16, $1695.0, waited 7.185 sec.
/halmstad, -10, $1641.0, waited 2.022 sec.
/helsingborg, 18, $1957.0, waited 10.15 sec.
/jonkoping, 16, $1777.0, waited 5.163 sec.
/karlstad, -10, $1730.0, waited 6.004 sec.
/lulea, -10, $1599.0, waited 4.42 sec.
/malmo, 140, $2078.0, waited 1.714 sec.
/norrkoping, 24, $1752.0, waited 9.786 sec.
/pitea, -10, $nan, waited 1.179 sec.
/skelleftea, -10, $1807.0, waited 5.508 sec.
/stockholm, 266, $2660.0, waited 10.45 sec.
/umea, -10, $1634.0, waited 7.519 sec.

/uppsala, 31, $2020.0, waited 8.791 sec.
/visby, -10, $1755.0, waited 2.602 sec.
/vasteras, -10, $1780.0, waited 1.155 sec.
/vaxjo, -10, $1557.0, waited 1.483 sec.
/orebro, -10, $1719.0, waited 4.401 sec.
/aarau, -10, $3163.0, waited 5.362 sec.
/basel, 61, $3233.0, waited 1.457 sec.
/bern, 126, $3198.0, waited 8.358 sec.
/geneva, 144, $4717.0, waited 0.612 sec.
/lausanne, 96, $3365.0, waited 10.03 sec.
/lugano, 52, $3430.0, waited 9.593 sec.
/neuchatel, -10, $2898.0, waited 8.79 sec.
/schaffhausen, -10, $2968.0, waited 3.636 sec.
/sion, 42, $2575.0, waited 2.602 sec.
/st-gallen, 14, $2825.0, waited 2.105 sec.
/zurich, 510, $4151.0, waited 6.291 sec.
/aleppo, -10, $215.0, waited 9.57 sec.
/damascus, -10, $220.0, waited 2.93 sec.
/homs, -10, $735.0, waited 7.621 sec.
/palmyra, -10, $nan, waited 9.795 sec.
/hsinchu-city, -10, $1373.0, waited 6.6 sec.
/hualian, -10, $nan, waited 4.548 sec.
/kao-hsiung, -10, $1232.0, waited 6.018 sec.
/kaohsiung-city, -10, $1397.0, waited 2.962 sec.
/taichung-city, 10, $1534.0, waited 3.234 sec.
/tainan-city, 100, $1021.0, waited 9.756 sec.
/taipei, 155, $1877.0, waited 0.6717 sec.
/yun-lin, -10, $1452.0, waited 5.568 sec.
/dushanbe, 94, $614.0, waited 4.953 sec.
/arusha, 18, $979.0, waited 1.028 sec.
/bagamoyo, 32, $nan, waited 7.367 sec.
/dar-es-salaam, 49, $1429.0, waited 3.915 sec.
/dodoma, -10, $477.0, waited 6.038 sec.
/iringa, -10, $nan, waited 6.862 sec.
/kigoma, -10, $nan, waited 1.751 sec.
/mbeya, -10, $nan, waited 2.371 sec.
/morogoro, -10, $nan, waited 4.806 sec.
/moshi, -10, $545.0, waited 5.29 sec.
/mtwara, 57, $nan, waited 2.389 sec.
/mwanza, -10, $878.0, waited 8.229 sec.
/songea, -10, $nan, waited 9.536 sec.
/sumbawanga, -10, $nan, waited 0.9228 sec.
/tabora, -10, $nan, waited 7.751 sec.
/tanga, -10, $nan, waited 5.053 sec.
/uyovu, 16, $nan, waited 7.063 sec.
/zanzibar, 45, $782.0, waited 5.004 sec.
/ayutthaya, -10, $nan, waited 7.812 sec.
/bangkok, 247, $1399.0, waited 4.887 sec.
/chaiyaphum, -10, $990.0, waited 2.404 sec.
/changwat-rayong, -10, $692.0, waited 2.838 sec.
/chiang-mai, 143, $883.0, waited 3.124 sec.
/chiang-rai, -10, $645.0, waited 4.221 sec.
/chumphon, 12, $nan, waited 9.031 sec.
/hua-hin, 36, $1438.0, waited 10.06 sec.
/khon-kaen, -10, $714.0, waited 9.308 sec.
/klaeng, 14, $870.0, waited 1.627 sec.
/ko-tao, -10, $nan, waited 6.237 sec.
/lampang, 27, $nan, waited 8.454 sec.
/maha-sarakham, -10, $nan, waited 4.557 sec.
/nakhon-ratchasima, -10, $nan, waited 0.8076 sec.
/nakhon-si-thammarat, -10, $nan, waited 8.113 sec.
/pattaya, 67, $963.0, waited 4.282 sec.
/phetchabun, -10, $nan, waited 1.294 sec.
/phitsanulok, -10, $1029.0, waited 2.918 sec.
/phuket, 66, $1327.0, waited 3.836 sec.
/ratchaburi, -10, $nan, waited 9.294 sec.
/sakon-nakhon, -10, $579.0, waited 7.119 sec.
/sattahip, -10, $nan, waited 4.719 sec.
/si-racha, -10, $1218.0, waited 1.545 sec.
/suphan-buri, -10, $nan, waited 5.921 sec.
/surat-thani, -10, $914.0, waited 7.175 sec.
/trang, -10, $nan, waited 7.559 sec.
/ubon-ratchathani, -10, $515.0, waited 6.708 sec.
/udon-thani, -10, $774.0, waited 5.457 sec.
/kara-togo, -10, $nan, waited 4.525 sec.
/lome, -10, $912.0, waited 4.25 sec.
/nuku-alofa-tonga, -10, $nan, waited 7.372 sec.
/mon-repos, -10, $1409.0, waited 3.2 sec.
/port-of-spain, 174, $1451.0, waited 8.504 sec.
/beja, -10, $350.0, waited 10.37 sec.
/bizerte, -10, $400.0, waited 7.76 sec.
/gabes, -10, $365.0, waited 9.599 sec.
/gafsa, 55, $514.0, waited 5.14 sec.
/hammamet, -10, $nan, waited 9.783 sec.
/jendouba, -10, $nan, waited 2.967 sec.
/kairouan, -10, $nan, waited 10.3 sec.
/kasserine, -10, $nan, waited 8.296 sec.
/midoun, 25, $nan, waited 8.185 sec.
/nabeul, -10, $550.0, waited 1.529 sec.
/sfax, -10, $589.0, waited 6.874 sec.
/sousse, 51, $529.0, waited 9.168 sec.
/tunis, 349, $714.0, waited 1.111 sec.
/adana, 114, $380.0, waited 9.281 sec.
/adapazar, 21, $284.0, waited 4.108 sec.
/afyonkarahisar, -10, $658.0, waited 4.14 sec.
/aksaray, -10, $nan, waited 8.409 sec.
/alanya, 71, $512.0, waited 2.445 sec.
/ankara, 627, $621.0, waited 8.302 sec.
/antalya, 284, $599.0, waited 2.274 sec.
/antioch, -10, $293.0, waited 3.53 sec.
/aydin, 13, $328.0, waited 10.44 sec.
/balkesir, -10, $423.0, waited 8.541 sec.
/bandirma, 12, $nan, waited 6.21 sec.
/batman, -10, $nan, waited 3.419 sec.
/bursa, 117, $500.0, waited 7.623 sec.
/denizli, 41, $328.0, waited 8.788 sec.
/diyarbakr, -10, $356.0, waited 3.503 sec.
/dorylaeum, -10, $1166.0, waited 7.298 sec.
/edirne, -10, $323.0, waited 3.788 sec.
/elazg, 16, $356.0, waited 7.042 sec.
/erzincan, -10, $nan, waited 2.519 sec.
/erzurum, 27, $448.0, waited 1.706 sec.
/eskisehir-province, 12, $308.0, waited 3.509 sec.
/gaziantep, 64, $410.0, waited 0.5474 sec.
/gebze, 14, $349.0, waited 3.282 sec.
/isparta, 12, $646.0, waited 6.82 sec.
/istanbul, 1678, $730.0, waited 8.164 sec.
/kahramanmaras, -10, $329.0, waited 4.427 sec.
/karaman, -10, $nan, waited 6.873 sec.
/kayseri, 41, $302.0, waited 5.01 sec.
/kirikkale, -10, $288.0, waited 4.705 sec.
/kirklareli, 10, $309.0, waited 5.76 sec.
/konya, 202, $370.0, waited 1.545 sec.
/kutahya, -10, $nan, waited 6.134 sec.
/malatya, -10, $375.0, waited 3.947 sec.
/mersin, 71, $374.0, waited 1.606 sec.
/nazilli, -10, $566.0, waited 7.833 sec.
/ordu, -10, $nan, waited 8.934 sec.
/osmaniye, 59, $1154.0, waited 6.297 sec.
/samsun, 22, $332.0, waited 10.48 sec.
/sanliurfa, 12, $359.0, waited 5.737 sec.
/siirt, -10, $280.0, waited 2.839 sec.
/sivas, -10, $1768.0, waited 6.055 sec.
/tekirdag, 56, $372.0, waited 6.091 sec.
/trabzon, 22, $464.0, waited 4.155 sec.
/turgutlu, -10, $nan, waited 5.575 sec.
/turhal, 58, $582.0, waited 2.908 sec.
/usak, -10, $779.0, waited 10.32 sec.
/van, -10, $nan, waited 6.978 sec.
/zonguldak, 10, $nan, waited 0.6374 sec.
/corum, -10, $nan, waited 4.984 sec.
/iskenderun, -10, $249.0, waited 7.794 sec.
/izmir, 294, $605.0, waited 8.892 sec.
/izmit, 53, $331.0, waited 1.396 sec.
/ashkhabad, -10, $1438.0, waited 5.53 sec.
/turkmenabat, -10, $nan, waited 8.96 sec.
/grand-turk-turks-and-caicos-islands, -10, $2707.0, waited 1.743 sec.
/providenciales, 51, $3610.0, waited 9.133 sec.
/funafuti-tuvalu, -10, $nan, waited 8.483 sec.
/charlotte-amalie, 38, $2821.0, waited 5.368 sec.
/christiansted, 20, $2457.0, waited 7.974 sec.
/cruz-bay, -10, $nan, waited 1.215 sec.
/arua, -10, $nan, waited 4.374 sec.
/gulu, -10, $781.0, waited 3.556 sec.
/kampala, 102, $1145.0, waited 8.546 sec.
/kasese, -10, $539.0, waited 8.728 sec.
/lira, -10, $nan, waited 3.761 sec.
/mbale, -10, $1167.0, waited 1.883 sec.
/njeru, -10, $nan, waited 10.17 sec.
/alchevskk, -10, $nan, waited 5.134 sec.
/berdyanskk, 10, $nan, waited 3.523 sec.
/bila-tserkva, -10, $nan, waited 4.088 sec.
/cherkasy, 20, $619.0, waited 6.034 sec.
/chernihiv, -10, $614.0, waited 4.826 sec.
/chernivtsi, -10, $nan, waited 10.28 sec.
/dnipro, 71, $750.0, waited 5.659 sec.
/donetsk, 22, $367.0, waited 4.798 sec.
/ivano-frankivskk, 131, $500.0, waited 7.694 sec.
/kamianets-podilskyi, -10, $nan, waited 0.6351 sec.
/kerch, -10, $nan, waited 3.734 sec.
/kharkiv, 87, $766.0, waited 9.118 sec.
/kherson, 21, $534.0, waited 9.02 sec.
/kirovohrad, -10, $991.0, waited 0.6539 sec.
/kremenchuk, -10, $461.0, waited 4.318 sec.
/kryvyy-rih, -10, $nan, waited 9.145 sec.
/kyiv, 350, $1272.0, waited 7.895 sec.
/luhanskk, -10, $nan, waited 2.029 sec.
/lutsk, -10, $942.0, waited 10.32 sec.
/lviv, 53, $740.0, waited 8.98 sec.
/mariupol, 16, $544.0, waited 7.258 sec.
/melitopol, -10, $nan, waited 2.455 sec.
/mykolayiv, -10, $617.0, waited 8.5 sec.
/odessa, 106, $736.0, waited 6.959 sec.
/pavlohrad, -10, $nan, waited 10.03 sec.
/poltava, 51, $524.0, waited 8.586 sec.
/rivne, 26, $580.0, waited 1.213 sec.
/sevastopol, -10, $811.0, waited 0.671 sec.
/simferopol, 31, $660.0, waited 9.124 sec.
/sumy, 18, $841.0, waited 1.318 sec.
/syeverodonetskk, 43, $498.0, waited 8.55 sec.
/ternopil, -10, $nan, waited 10.03 sec.
/uzhhorod, -10, $540.0, waited 3.132 sec.
/vinnytsya, 27, $439.0, waited 1.863 sec.
/zaporizhzhya, 62, $534.0, waited 6.782 sec.
/zhytomyr, -10, $588.0, waited 1.969 sec.
/abu-dhabi, 136, $2887.0, waited 5.969 sec.
/al-ain, 10, $2132.0, waited 8.628 sec.
/dubai, 780, $2395.0, waited 6.736 sec.
/fujairah, -10, $1607.0, waited 3.758 sec.

/ras-al-khaymahs-al-khaymah, 58, $1549.0, waited 3.344 sec.
/sharjah, 143, $1572.0, waited 7.969 sec.
/aberdeen, -10, $2051.0, waited 2.413 sec.
/aberystwyth, 10, $2282.0, waited 9.661 sec.
/belfast, 92, $1900.0, waited 5.683 sec.
/birmingham-united-kingdom, 122, $2074.0, waited 1.15 sec.
/brighton-and-hove, 111, $3125.0, waited 2.605 sec.
/bristol, 105, $2650.0, waited 0.5503 sec.
/cambridge, 94, $2714.0, waited 1.514 sec.
/cardiff, 35, $2028.0, waited 10.32 sec.
/coventry, 23, $2468.0, waited 3.604 sec.
/dundee, -10, $1767.0, waited 9.588 sec.
/edinburgh, 330, $2716.0, waited 5.994 sec.
/exeter, -10, $2058.0, waited 2.371 sec.
/glasgow, 126, $1967.0, waited 10.02 sec.
/gloucester, 11, $2252.0, waited 5.648 sec.
/inverness, -10, $2742.0, waited 5.868 sec.
/ipswich, -10, $2164.0, waited 1.278 sec.
/kingston-upon-hull, 46, $2200.0, waited 10.08 sec.
/leeds, 147, $2023.0, waited 4.516 sec.
/leicester, 53, $1778.0, waited 9.14 sec.
/liverpool, 203, $1839.0, waited 3.447 sec.
/london, 1289, $3857.0, waited 2.575 sec.
/luton, -10, $3368.0, waited 5.725 sec.
/manchester, 233, $2290.0, waited 7.443 sec.
/newcastle-upon-tyne, 44, $1994.0, waited 2.191 sec.
/northampton, 48, $2037.0, waited 4.468 sec.
/norwich, 24, $2051.0, waited 4.039 sec.
/nottingham, 85, $1771.0, waited 9.269 sec.
/oxford, 18, $2984.0, waited 7.414 sec.
/perth-scotland, -10, $2048.0, waited 3.525 sec.
/peterborough, -10, $1960.0, waited 7.989 sec.
/plymouth, 34, $2117.0, waited 6.969 sec.
/poole, 12, $2508.0, waited 3.049 sec.
/portsmouth, 41, $2192.0, waited 4.26 sec.
/preston, -10, $1865.0, waited 1.703 sec.
/reading-berkshire, 76, $2651.0, waited 9.38 sec.
/sheffield, 115, $1527.0, waited 2.449 sec.
/southampton, 128, $2331.0, waited 4.619 sec.
/southend-on-sea, 12, $2250.0, waited 9.615 sec.
/stoke-on-trent, 73, $2077.0, waited 10.12 sec.
/sunderland, -10, $1876.0, waited 6.907 sec.
/swansea, -10, $1929.0, waited 3.572 sec.
/york, 25, $2140.0, waited 0.562 sec.
/akron, 91, $1752.0, waited 7.85 sec.
/albany, 110, $2251.0, waited 0.5184 sec.
/albuquerque, 304, $1992.0, waited 1.18 sec.
/allentown-pennsylvania, 35, $1831.0, waited 3.412 sec.
/amarillo, 71, $1830.0, waited 0.7195 sec.
/anchorage, 190, $2438.0, waited 7.645 sec.
/ann-arbor, 55, $2488.0, waited 4.776 sec.
/arcata, -10, $2257.0, waited 9.558 sec.
/arlington-texas, 36, $1786.0, waited 3.414 sec.
/asheville, 152, $2402.0, waited 4.745 sec.
/athens-georgia, 63, $1582.0, waited 2.272 sec.
/atlanta, 396, $2174.0, waited 2.968 sec.
/augusta-georgia, 53, $1729.0, waited 4.59 sec.
/austin, 351, $2648.0, waited 8.536 sec.
/babylon, 26, $3327.0, waited 2.628 sec.
/bakersfield, 133, $1939.0, waited 9.481 sec.
/baltimore, 161, $2498.0, waited 5.625 sec.
/baton-rouge, -10, $1864.0, waited 7.088 sec.
/beaverton-oregon, 86, $2976.0, waited 5.153 sec.
/berkeley, 128, $4447.0, waited 0.9793 sec.
/billings-montana, 100, $1868.0, waited 3.522 sec.
/birmingham-alabama, 124, $1886.0, waited 7.451 sec.
/bismarck-north-dakota, -10, $1877.0, waited 3.131 sec.
/boise, 224, $2278.0, waited 10.45 sec.
/boston, 329, $3521.0, waited 1.103 sec.
/boulder-colorado, 169, $2908.0, waited 4.138 sec.
/bozeman-montana, -10, $2167.0, waited 4.327 sec.
/bridgeport-connecticut, 15, $2367.0, waited 2.319 sec.
/buffalo, 84, $1842.0, waited 6.108 sec.
/burlington-massachusetts, 19, $3066.0, waited 10.45 sec.
/burlington, 18, $2651.0, waited 9.168 sec.
/butte-mt, -10, $1470.0, waited 1.687 sec.
/cedar-falls-iowa, 73, $1405.0, waited 10.13 sec.
/cedar-rapids, -10, $1584.0, waited 9.486 sec.
/charleston-south-carolina, 122, $2684.0, waited 0.5984 sec.
/charlotte-united-states, 200, $2729.0, waited 6.969 sec.
/charlottesville-virginia, 44, $2174.0, waited 1.95 sec.
/chattanooga, 98, $1878.0, waited 5.871 sec.
/chicago, 606, $2841.0, waited 2.516 sec.
/cincinnati, 134, $1870.0, waited 6.959 sec.
/cleveland, 84, $1910.0, waited 7.364 sec.
/cocoa-beach-florida, 18, $2675.0, waited 7.054 sec.
/colorado-springs, 74, $2095.0, waited 0.892 sec.
/columbia-south-carolina, 36, $1643.0, waited 2.201 sec.
/columbus, 223, $1955.0, waited 2.582 sec.
/corpus-christi, 21, $1815.0, waited 9.99 sec.
/dallas, 425, $2537.0, waited 5.372 sec.
/denver, 355, $2810.0, waited 0.7105 sec.
/des-moines, 109, $1925.0, waited 6.218 sec.
/detroit, 177, $2331.0, waited 2.162 sec.
/durango-colorado, -10, $nan, waited 6.612 sec.
/durham, 88, $1972.0, waited 8.329 sec.
/el-paso, 113, $1512.0, waited 1.648 sec.
/erie-pennsylvania, -10, $1599.0, waited 6.477 sec.
/eugene, 147, $2379.0, waited 3.387 sec.
/fargo, -10, $1754.0, waited 4.369 sec.
/flint-michigan, -10, $1521.0, waited 1.126 sec.
/florence-alabama, -10, $1695.0, waited 6.668 sec.
/fort-collins, 144, $2390.0, waited 10.46 sec.
/fort-lauderdale, 235, $2597.0, waited 7.945 sec.
/fort-wayne, 29, $1548.0, waited 5.389 sec.
/fort-worth, 64, $2198.0, waited 10.2 sec.
/fresno, 16, $2109.0, waited 1.968 sec.
/gainesville, 48, $1760.0, waited 5.849 sec.
/grand-rapids, 23, $2020.0, waited 8.7 sec.
/green-bay-wisconsin, 83, $2128.0, waited 8.973 sec.
/greensboro, 34, $1641.0, waited 2.646 sec.
/greenville-south-carolina, 45, $1816.0, waited 9.326 sec.
/harrisburg-pennsylvania, -10, $2006.0, waited 7.823 sec.
/hartford-connecticut, 91, $2425.0, waited 6.931 sec.
/hilton-head-island, -10, $2403.0, waited 1.87 sec.
/honolulu, 254, $3626.0, waited 0.6382 sec.
/houston, 748, $2226.0, waited 7.898 sec.
/huntsville-alabama, 83, $1873.0, waited 8.468 sec.
/indianapolis, 72, $1927.0, waited 4.228 sec.
/iowa-city, 19, $1840.0, waited 1.276 sec.
/irvine, 204, $3539.0, waited 10.19 sec.
/ithaca-new-york, 15, $2207.0, waited 1.62 sec.
/jackson-mississippi, 39, $2014.0, waited 3.288 sec.
/jacksonville, 307, $2117.0, waited 6.816 sec.
/jersey-city, 170, $3545.0, waited 3.39 sec.
/kansas-city, 63, $1996.0, waited 7.553 sec.
/knoxville-tn, 74, $1776.0, waited 6.766 sec.
/kodiak-alaska, -10, $1896.0, waited 4.185 sec.
/lafayette-louisiana, -10, $1783.0, waited 7.485 sec.
/laguna-niguel-california, 23, $3364.0, waited 2.274 sec.
/las-vegas, 431, $2028.0, waited 6.212 sec.
/lawrence-kansas, 43, $1658.0, waited 2.348 sec.
/lexington, 83, $1498.0, waited 10.15 sec.
/lincoln, 20, $1548.0, waited 5.0 sec.
/little-rock-arkansas, 51, $1911.0, waited 7.3 sec.
/long-beach, 69, $3495.0, waited 0.7848 sec.
/los-angeles, 914, $3602.0, waited 7.225 sec.
/louisville, 67, $1544.0, waited 1.565 sec.
/lubbock, -10, $1666.0, waited 8.679 sec.
/lynchburg-virginia, -10, $1715.0, waited 1.983 sec.
/madison, 146, $2178.0, waited 6.414 sec.
/maui, 32, $3141.0, waited 7.802 sec.
/mcallen-texas, 20, $1512.0, waited 6.124 sec.
/memphis, 76, $1647.0, waited 4.712 sec.
/miami, 513, $3156.0, waited 3.163 sec.
/midland-texas, -10, $2363.0, waited 7.244 sec.
/milwaukee, 113, $1993.0, waited 5.315 sec.
/minneapolis, 179, $2370.0, waited 4.307 sec.
/moab-utah, 49, $1752.0, waited 3.131 sec.
/mobile-alabama, 91, $1725.0, waited 7.139 sec.
/modesto, 79, $2066.0, waited 2.82 sec.
/montclair-new-jersey, 26, $3338.0, waited 8.291 sec.
/mount-pleasant-sc, 20, $2449.0, waited 6.271 sec.
/mountain-view-california, 57, $5121.0, waited 9.764 sec.
/naknek, 15, $nan, waited 3.91 sec.
/nantucket, -10, $4006.0, waited 1.31 sec.
/nashville, 239, $2317.0, waited 1.474 sec.
/new-haven-connecticut, 41, $2394.0, waited 1.735 sec.
/new-orleans, 250, $2091.0, waited 7.987 sec.
/new-york-city, 1011, $4346.0, waited 6.14 sec.
/newark, 139, $2584.0, waited 3.251 sec.
/niagara-falls-new-york, 28, $1479.0, waited 5.235 sec.
/oakland-california, 190, $4213.0, waited 2.724 sec.
/oklahoma-city, 129, $1822.0, waited 2.789 sec.
/omaha, 67, $1887.0, waited 8.947 sec.
/orlando, 178, $2310.0, waited 4.693 sec.
/palm-bay-florida, 17, $1939.0, waited 4.466 sec.
/palm-springs-california, 25, $2500.0, waited 8.978 sec.
/palo-alto, 54, $4492.0, waited 6.883 sec.
/pensacola-florida, 101, $2046.0, waited 0.9551 sec.
/philadelphia, 297, $2298.0, waited 8.989 sec.
/phoenix, 450, $2351.0, waited 1.239 sec.
/pittsburgh, 124, $2194.0, waited 4.941 sec.
/portland, 456, $2921.0, waited 2.568 sec.
/providence-rhode-island, 101, $2593.0, waited 8.846 sec.
/provo-utah, 111, $2110.0, waited 4.412 sec.
/raleigh-north-carolina, 223, $2141.0, waited 9.799 sec.

/reno, 192, $2236.0, waited 8.715 sec.
/richmond-virginia, 133, $1887.0, waited 4.59 sec.
/riverside, 56, $2510.0, waited 4.089 sec.
/roanoke-virginia, 27, $1762.0, waited 8.482 sec.
/rochester-new-york, 116, $1931.0, waited 0.6479 sec.
/rockford-illinois, 31, $nan, waited 9.542 sec.
/sacramento, 221, $2684.0, waited 4.588 sec.
/salt-lake-city, 230, $2308.0, waited 7.833 sec.
/san-antonio-california, -10, $1832.0, waited 5.724 sec.
/san-antonio-texas, 395, $2191.0, waited 2.237 sec.
/san-bernardino-california, 54, $2752.0, waited 4.219 sec.
/san-diego, 434, $3602.0, waited 6.079 sec.
/san-francisco, 278, $4474.0, waited 1.824 sec.
/san-jose-california, 284, $3863.0, waited 5.198 sec.
/san-luis-obispo-california, 92, $3086.0, waited 7.655 sec.
/santa-ana, 149, $2877.0, waited 3.283 sec.
/santa-barbara-california, 79, $3626.0, waited 4.602 sec.
/santa-cruz-california, 65, $3517.0, waited 8.089 sec.
/santa-fe-new-mexico, 19, $2397.0, waited 2.953 sec.
/savannah-georgia, 82, $2043.0, waited 10.04 sec.
/scottsdale, 106, $2739.0, waited 3.514 sec.
/seattle, 792, $3370.0, waited 9.478 sec.
/shreveport, 47, $1712.0, waited 6.617 sec.
/spokane-washington, 189, $2211.0, waited 6.392 sec.
/springfield-illinois, 14, $1597.0, waited 4.044 sec.
/springfield-massachusetts, 58, $2081.0, waited 2.246 sec.
/springfield-missouri, 71, $1316.0, waited 2.247 sec.
/st-louis, 268, $1978.0, waited 3.95 sec.
/st-petersburg-florida, 100, $2534.0, waited 5.081 sec.
/stamford, 72, $3028.0, waited 1.234 sec.
/staunton-virginia, 48, $2049.0, waited 7.681 sec.
/stockton, -10, $2104.0, waited 7.985 sec.
/tacoma, 187, $2489.0, waited 8.283 sec.
/tallahassee, 209, $1980.0, waited 6.069 sec.
/tampa, 309, $2440.0, waited 3.016 sec.
/tempe-arizona, 153, $2168.0, waited 0.9221 sec.
/toledo-ohio, 40, $1727.0, waited 0.6031 sec.
/traverse-city-michigan, 79, $2044.0, waited 4.463 sec.
/tucson, 166, $1965.0, waited 8.546 sec.
/tulsa-oklahoma, 216, $1770.0, waited 2.286 sec.
/tyler-texas, 13, $1732.0, waited 8.879 sec.
/vancouver-washington, 26, $2152.0, waited 9.928 sec.
/virginia-beach, 89, $2122.0, waited 2.812 sec.
/walnut-creek-california, -10, $3580.0, waited 8.867 sec.
/washington-d-c, 456, $3435.0, waited 6.615 sec.
/waterbury-connecticut, -10, $2806.0, waited 1.158 sec.
/west-lafayette-indiana, 32, $2083.0, waited 10.41 sec.
/wichita, 57, $1579.0, waited 1.073 sec.
/wilmington-delaware, -10, $2098.0, waited 10.29 sec.
/youngstown-ohio, 101, $1452.0, waited 10.24 sec.
/zanesville-ohio, -10, $nan, waited 7.778 sec.
/maldonado, 34, $962.0, waited 4.646 sec.
/melo, -10, $708.0, waited 3.413 sec.
/montevideo, 660, $1314.0, waited 9.395 sec.
/paysandu, 27, $789.0, waited 3.192 sec.
/punta-del-este, 73, $1125.0, waited 10.23 sec.
/rivera, 11, $nan, waited 7.82 sec.
/tacuarembo, -10, $967.0, waited 7.265 sec.
/angren, -10, $nan, waited 10.14 sec.
/kokand, -10, $632.0, waited 8.792 sec.
/namangan, 33, $nan, waited 1.19 sec.
/navoiy, -10, $nan, waited 8.915 sec.
/nukus, 74, $415.0, waited 3.142 sec.
/qarshi, 22, $nan, waited 5.457 sec.
/samarkand, 55, $nan, waited 6.168 sec.
/tashkent, 577, $652.0, waited 2.373 sec.
/termez, -10, $nan, waited 2.004 sec.
/urgench, 14, $630.0, waited 5.73 sec.
/zarafshon, 22, $nan, waited 5.024 sec.
/port-vila-vanuatu, -10, $1997.0, waited 5.569 sec.
/acarigua, -10, $nan, waited 6.229 sec.
/alto-barinas, -10, $nan, waited 8.839 sec.
/anaco, 14, $nan, waited 6.762 sec.
/barcelona-venezuela, -10, $nan, waited 1.865 sec.
/barquisimeto, 158, $187.0, waited 8.061 sec.
/calabozo, 34, $nan, waited 2.245 sec.
/caracas, 1473, $140.0, waited 1.383 sec.
/carupano, 37, $nan, waited 5.498 sec.
/ciudad-bolivar, 35, $nan, waited 5.459 sec.
/ciudad-guayana, 53, $110.0, waited 0.6971 sec.
/coro, 84, $nan, waited 9.442 sec.
/cumana, -10, $45.0, waited 3.525 sec.
/el-tigre, -10, $6.0, waited 6.051 sec.
/guanare, -10, $nan, waited 3.818 sec.
/maracaibo, 160, $149.0, waited 9.234 sec.
/maturin, 36, $50.0, waited 3.521 sec.
/punto-fijo, -10, $nan, waited 9.038 sec.
/santa-teresa, -10, $nan, waited 7.288 sec.
/turmero, 24, $nan, waited 3.055 sec.
/valencia-venezuela, 33, $24.0, waited 8.942 sec.
/da-lat, -10, $nan, waited 7.556 sec.
/da-nang, 22, $941.0, waited 9.905 sec.
/haiphong, -10, $1009.0, waited 7.178 sec.
/hanoi, 119, $983.0, waited 9.445 sec.
/ho-chi-minh-city, 114, $1343.0, waited 2.325 sec.
/hue, -10, $nan, waited 2.314 sec.
/long-xuyen, -10, $nan, waited 6.744 sec.
/nha-trang, -10, $844.0, waited 1.278 sec.
/phan-thiet, -10, $nan, waited 5.213 sec.
/quy-nhon, -10, $nan, waited 4.143 sec.
/thanh-hoa, 21, $nan, waited 0.7002 sec.
/tuy-hoa, -10, $nan, waited 4.183 sec.
/viet-tri, -10, $nan, waited 0.8466 sec.
/vinh-long, -10, $nan, waited 10.43 sec.
/vung-tau, -10, $779.0, waited 6.994 sec.
/el-aaiun, -10, $nan, waited 4.616 sec.
/aden, 26, $1639.0, waited 5.422 sec.
/al-mukalla, -10, $nan, waited 6.748 sec.
/ibb, -10, $nan, waited 3.163 sec.
/sana, 75, $1153.0, waited 5.79 sec.
/chingola, -10, $nan, waited 5.259 sec.
/chipata, -10, $nan, waited 7.188 sec.
/kabwe, -10, $1323.0, waited 8.683 sec.
/kasama, -10, $nan, waited 3.314 sec.
/livingstone, -10, $nan, waited 5.995 sec.
/lusaka, 54, $1049.0, waited 7.228 sec.
/ndola, -10, $1156.0, waited 4.98 sec.
/bulawayo, -10, $932.0, waited 6.36 sec.
/chinhoyi, -10, $nan, waited 6.902 sec.
/gweru, -10, $nan, waited 6.599 sec.
/harare, 102, $1580.0, waited 4.614 sec.
/kadoma, -10, $nan, waited 4.576 sec.
/marondera, -10, $nan, waited 2.653 sec.
/masvingo, -10, $nan, waited 7.3 sec.
/mutare, -10, $nan, waited 8.826 sec.
/zvishavane-district, 11, $nan, waited 2.686 sec.

In [74]:
# Error occurred mid-page if all four not same length -> re-scrape

print(len(rent_85m2_expens), len(mobile_wifi_128gb), len(list_COL_sin1), len(list_n_prices))

694 694 694 694

In [75]:
# Concatenate into full COL dataset

list_tuples2 = list(zip(rent_85m2_expens,
                      rent_85m2_normal,
                      rent_45m2_expens,
                      rent_45m2_normal,
                      eatout_lunch,
                      eatout_dinner,
                      taxi_5mi,
                      gas_liter,
                      pubtrans_monthly,
                      internet_monthly,
                      TV_40in,
                      cappuccino,
                      mobile_wifi_128gb))

list_tuples3 = list(zip(list_COL_sin1,
                       list_COL_fam4))

list_tuples4 = list(zip(list_n_prices,
                      list_n_people))

df2 = pd.DataFrame(list_tuples2, columns = list_feature_names)
df3 = pd.DataFrame(list_tuples3, columns = ['COL (Family of 4)',
                                            'COL (Single of 1)'])
df4 = pd.DataFrame(list_tuples4, columns = ['No. Prices',
                                            'No. Contributors'])

In [77]:
# df1_split = df1[1781:].reset_index(drop=True)  #resetting renames
# df1_split

,City,Country,URL
0,Al Mubarraz,Saudi Arabia,https://www.expatistan.com/cost-of-living/al-m...
1,Al Qurayyat,Saudi Arabia,https://www.expatistan.com/cost-of-living/al-q...
2,Arar,Saudi Arabia,https://www.expatistan.com/cost-of-living/arar
3,Buraidah,Saudi Arabia,https://www.expatistan.com/cost-of-living/bura...
4,Dammam,Saudi Arabia,https://www.expatistan.com/cost-of-living/dammam
...,...,...,...
689,Kadoma,Zimbabwe,https://www.expatistan.com/cost-of-living/kadoma
690,Marondera,Zimbabwe,https://www.expatistan.com/cost-of-living/maro...
691,Masvingo,Zimbabwe,https://www.expatistan.com/cost-of-living/masv...
692,Mutare,Zimbabwe,https://www.expatistan.com/cost-of-living/mutare
693,Zvishavane District,Zimbabwe,https://www.expatistan.com/cost-of-living/zvis...

In [78]:
# check df1 name before joining

df_cities_test = pd.concat([df1_split, df2, df3, df4], axis=1, ignore_index=True)
df_cities_test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,Al Mubarraz,Saudi Arabia,https://www.expatistan.com/cost-of-living/al-m...,1200.0,533.0,800.0,400.0,13.00,27.0,5.83,0.13,240.0,27.0,533.0,3.73,NaN,1514.0,3444.0,-10,-5
1,Al Qurayyat,Saudi Arabia,https://www.expatistan.com/cost-of-living/al-q...,320.0,267.0,NaN,NaN,3.38,16.0,NaN,NaN,NaN,NaN,294.0,1.87,NaN,NaN,NaN,-10,-5
2,Arar,Saudi Arabia,https://www.expatistan.com/cost-of-living/arar,754.0,302.0,307.0,213.0,4.35,9.0,16.00,0.52,NaN,28.0,233.0,2.13,133.0,920.0,2101.0,-10,-5
3,Buraidah,Saudi Arabia,https://www.expatistan.com/cost-of-living/bura...,517.0,468.0,365.0,232.0,7.00,NaN,NaN,0.33,NaN,38.0,312.0,4.56,666.0,933.0,2316.0,12,-5
4,Dammam,Saudi Arabia,https://www.expatistan.com/cost-of-living/dammam,927.0,548.0,627.0,367.0,9.00,23.0,19.00,0.42,34.0,49.0,293.0,3.62,491.0,1218.0,2666.0,74,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689,Kadoma,Zimbabwe,https://www.expatistan.com/cost-of-living/kadoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
690,Marondera,Zimbabwe,https://www.expatistan.com/cost-of-living/maro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
691,Masvingo,Zimbabwe,https://www.expatistan.com/cost-of-living/masv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
692,Mutare,Zimbabwe,https://www.expatistan.com/cost-of-living/mutare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
693,Zvishavane District,Zimbabwe,https://www.expatistan.com/cost-of-living/zvis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,-5

In [80]:
df_cities = pd.concat([df1_split, df2, df3, df4], axis=1, ignore_index=True)
# df_allcities = pd.concat([df1, df2, df3, df4], axis=1) # once 
df_cities.tail(20)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
674,Aden,Yemen,https://www.expatistan.com/cost-of-living/aden,1116.0,778.0,491.0,317.0,8.00,11.00,NaN,0.82,77.0,79.00,691.0,1.86,NaN,1639.0,3657.0,26,-5
675,Al Mukalla,Yemen,https://www.expatistan.com/cost-of-living/al-m...,411.0,NaN,598.0,NaN,3.73,NaN,NaN,1.25,NaN,143.00,957.0,1.20,NaN,NaN,NaN,-10,-5
676,Ibb,Yemen,https://www.expatistan.com/cost-of-living/ibb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
677,San‘a’,Yemen,https://www.expatistan.com/cost-of-living/sana,571.0,576.0,1178.0,418.0,10.00,17.00,NaN,0.82,26.0,82.00,293.0,3.30,120.0,1153.0,2735.0,75,-5
678,Chingola,Zambia,https://www.expatistan.com/cost-of-living/chin...,606.0,454.0,485.0,242.0,43.00,18.00,NaN,0.67,NaN,NaN,333.0,NaN,NaN,NaN,NaN,-10,-5
679,Chipata,Zambia,https://www.expatistan.com/cost-of-living/chipata,606.0,273.0,NaN,NaN,1.51,4.24,NaN,0.81,NaN,3.03,91.0,1.51,NaN,NaN,NaN,-10,-5
680,Kabwe,Zambia,https://www.expatistan.com/cost-of-living/kabwe,1090.0,909.0,1212.0,454.0,2.83,24.00,NaN,0.77,24.0,12.00,182.0,3.03,55.0,1323.0,2227.0,-10,-5
681,Kasama,Zambia,https://www.expatistan.com/cost-of-living/kasama,NaN,NaN,NaN,NaN,NaN,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
682,Livingstone,Zambia,https://www.expatistan.com/cost-of-living/livi...,417.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,NaN,97.0,NaN,NaN,NaN,NaN,-10,-5
683,Lusaka,Zambia,https://www.expatistan.com/cost-of-living/lusaka,803.0,598.0,576.0,360.0,8.00,17.00,16.0,1.04,23.0,24.00,345.0,1.77,287.0,1049.0,2061.0,54,14
684,Ndola,Zambia,https://www.expatistan.com/cost-of-living/ndola,1006.0,655.0,353.0,303.0,5.04,21.00,NaN,0.68,97.0,6.00,502.0,2.00,61.0,1156.0,2158.0,-10,-5
685,Bulawayo,Zimbabwe,https://www.expatistan.com/cost-of-living/bula...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,932.0,2283.0,-10,-5
686,Chinhoyi,Zimbabwe,https://www.expatistan.com/cost-of-living/chin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
687,Gweru,Zimbabwe,https://www.expatistan.com/cost-of-living/gweru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
688,Harare,Zimbabwe,https://www.expatistan.com/cost-of-living/harare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1580.0,3444.0,102,10
689,Kadoma,Zimbabwe,https://www.expatistan.com/cost-of-living/kadoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
690,Marondera,Zimbabwe,https://www.expatistan.com/cost-of-living/maro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
691,Masvingo,Zimbabwe,https://www.expatistan.com/cost-of-living/masv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
692,Mutare,Zimbabwe,https://www.expatistan.com/cost-of-living/mutare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
693,Zvishavane District,Zimbabwe,https://www.expatistan.com/cost-of-living/zvis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,-5

In [87]:
# Save your progress to disk!!

# df_cities1781_2474 = df_cities.copy()
# df_cities1781_2474.to_pickle('df_cities1781_2474')

# For quick recovery

# df_cities = pd.read_pickle(df_cities981_1780.pkl)

In [101]:
print(df_cities000_980.shape,  # last city: Pontianak, Indonesia
    df_cities981_1780.shape,   # last city: Sao Tome, ST&P
    df_cities1781_2474.shape)  # last city: Zvishavane District, Zimbabwe

(981, 20) (800, 20) (694, 20)

In [103]:
df_allcities

,City,Country,URL,rent_85m2_expens,rent_85m2_normal,rent_45m2_expens,rent_45m2_normal,eatout_lunch,eatout_dinner,taxi_5mi,gas_liter,pubtrans_monthly,internet_monthly,TV_40in,cappuccino,mobile_wifi_128gb,COL (Family of 4),COL (Single of 1),No. Prices,No. Contributors
0,Kabul,Afghanistan,https://www.expatistan.com/cost-of-living/kabul,429.0,254.0,295.0,213.0,4.41,9.0,4.12,0.49,31.0,37.0,229.0,2.01,259.0,619.0,1438.0,206,13
1,Mariehamn,Aland Islands,https://www.expatistan.com/cost-of-living/mari...,1174.0,998.0,910.0,587.0,15.00,41.0,23.00,1.80,121.0,32.0,587.0,4.74,NaN,1934.0,4549.0,-10,-5
2,Durrës,Albania,https://www.expatistan.com/cost-of-living/durres,263.0,725.0,491.0,288.0,30.00,24.0,NaN,1.66,14.0,18.0,654.0,1.66,NaN,995.0,2516.0,-10,-5
3,Elbasan,Albania,https://www.expatistan.com/cost-of-living/elbasan,275.0,198.0,154.0,103.0,3.39,19.0,NaN,1.60,NaN,10.0,387.0,1.30,NaN,628.0,1916.0,31,-5
4,Korçë,Albania,https://www.expatistan.com/cost-of-living/korce,2073.0,343.0,820.0,375.0,6.00,24.0,20.00,1.63,85.0,13.0,458.0,1.67,NaN,1888.0,3964.0,-10,-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689,Kadoma,Zimbabwe,https://www.expatistan.com/cost-of-living/kadoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
690,Marondera,Zimbabwe,https://www.expatistan.com/cost-of-living/maro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
691,Masvingo,Zimbabwe,https://www.expatistan.com/cost-of-living/masv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
692,Mutare,Zimbabwe,https://www.expatistan.com/cost-of-living/mutare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10,-5
693,Zvishavane District,Zimbabwe,https://www.expatistan.com/cost-of-living/zvis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,-5

In [97]:
# # Needed to run b/c column names were dropped for 2nd and 3rd sets

# df_unlabeledcities = pd.concat([df_cities981_1780, 
#                           df_cities1781_2474], axis=0) # once

# df_unlabeledcities.columns = ['City', 'Country', 'URL', 
#                         'rent_85m2_expens', 'rent_85m2_normal',
#                         'rent_45m2_expens', 'rent_45m2_normal',
#                         'eatout_lunch', 'eatout_dinner',
#                         'taxi_5mi', 'gas_liter',
#                         'pubtrans_monthly', 'internet_monthly',
#                         'TV_40in', 'cappuccino', 'mobile_wifi_128gb',
#                         'COL (Family of 4)', 'COL (Single of 1)',
#                         'No. Prices', 'No. Contributors']

# df_allcities = pd.concat([df_cities000_980, 
#                           df_unlabeledcities], axis=0)

# df_allcities.shape

(2475, 20)

In [99]:
# Save your work

df_allcities.to_pickle('df_allcities')
df_allcities.to_csv('allcitiescsvcopy', index=False)

# For quick recovery

# df_allcities = pd.read_pickle(df_allcities.pkl)
# df_allcities = pd.read_csv('allcitiescsvcopy')

### (Not needed)

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

chromedriver = "/Applications/chromedriver" # path to the chromedriver executable
os.environ["webdriver.chrome.driver"] = chromedriver

In [ ]:
def currency_to_usd(url):
    chromedriver = "/Applications/chromedriver" 
    os.environ["webdriver.chrome.driver"] = chromedriver
    
    driver = webdriver.Chrome(chromedriver)
    driver.get(url)
    time.sleep(20)
    
    currency_dropdown = driver.find_element_by_id('change_currency')
    currency_dropdown.click()
    time.sleep(2)

    currency_dropdown.send_keys("USD - $ (Dollar)")
    time.sleep(2)

    soup_usd = BeautifulSoup(driver.page_source, 'html.parser')
    return soup_usd

In [ ]:
# Raw HTML for navigation (currency unconverted)
# Continue testing with Kabul

driver = webdriver.Chrome(chromedriver)
driver.get('https://www.expatistan.com/cost-of-living/kabul')
time.sleep(2)

currency_dropdown = driver.find_element_by_id('change_currency')
currency_dropdown.click()
time.sleep(2)

currency_dropdown.send_keys("USD - $ (Dollar)")
time.sleep(2)

soup_usd = BeautifulSoup(driver.page_source, 'html.parser')
soup_usd.prettify

# May not need Selenium for Expatistan...

In [ ]:
# Get cost of living for single person and family of four

# chunk = soup_usd.find('div', class_='cost-of-living-summary centered right-widget')
# COL_fam4_str = chunk.find_all('span', class_='price')[0].text
# COL_sin1_str = chunk.find_all('span', class_='price')[1].text

# print(str_COL_fam4, type(str_COL_fam4))

In [ ]:
## Step by step for single city
# 1. Import HTML from URL as BS object 

url = 'https://www.expatistan.com/cost-of-living/guayaquil'      # Guayaquil, Ecuador

response = requests.get(url)                              
# response.status_code
page = response.text
soup_usd = BeautifulSoup(page, "lxml")

# 2. Find corresponding text in BeatifulSoup object

feature = 'Basic lunchtime menu (including a drink) in the business district'

chunk = soup_usd.find('a', text=feature)
check = chunk.findNext().findNext()
    if check.name == 'tr':
        feature_value = chunk.findNext().text[2:-2]
    else:
        feature_value = chunk1.findNext().findNext().text[2:-2]

In [ ]:
url = 'https://www.expatistan.com/cost-of-living/buenos-aires?currency=USD'      # Guayaquil, Ecuador

response = requests.get(url)                              
# response.status_code
page = response.text
soup_usd = BeautifulSoup(page, "lxml")

# 2. Find corresponding text in BeatifulSoup object

chunk1 = soup_usd.find('a', text='Basic lunchtime menu (including a drink) in the business district')
check = chunk1.findNext().findNext()
check.name

In [ ]:
feature_value = chunk1.findNext().findNext()
        
        if feature_value[0] != '$':                              # causes errors in countries 
           feature_value = np.nan
        else:
            fv_str = feature_value.replace('$', '').replace(',', '')
            feature_value = float(fv_str)
        
        list_of_lists[i].append(feature_value)

# 3. Append to corresponding lists

list_n_prices = []
list_n_people = []

n_prices = contribution_tuple[0]
n_people = contribution_tuple[1]

list_n_prices.append(n_prices)
list_n_people.append(n_people)

print(list_n_prices, list_n_people)    # should be ['206'] ['13'] for Kabul

In [ ]:
# # Define function for getting numbers of contributions/contributors.

# import random
# from fake_useragent import UserAgent

# def get_contribution_info(url):
    
#     ua = UserAgent()
#     user_agent = {'User-agent': ua.random}                                   # new user_agent every iteration
    
#     response = requests.get(url, headers = user_agent)                       
#     page = response.text
#     soup = BeautifulSoup(page, "lxml")
    
#     if soup.find_all('div', class_='cost-of-living-summary centered right-widget'):    # Summary window must be present
#         chunk = soup.find_all('div', class_='accuracy-report')[-1].text                # evaluation always last on page
#         sentences = chunk.split('.')                                                   # split into sentences
#         sentence_raw = sentences[2].strip()                                            # select 3rd sentence in accuracy-report
#         sentence = sentence_raw.replace('less than ', '-')                             # flag cities with scarce data as negative for now
#         words = sentence.split(' ')
#         no_prices, no_people = words[4], words[8]
#     else:
#         no_prices, no_people = 'ERROR', 'ERROR'                        # flagged to filter out later

#     return no_prices, no_people

In [ ]:
# # Scrape contributor info with delay
# # Run overnight

# list_n_prices = []
# list_n_people = []

# for url in list_url2:
    
#     contribution_tuple = get_contribution_info(url)
#     n_prices = contribution_tuple[0]
#     n_people = contribution_tuple[1]
    
#     list_n_prices.append(n_prices)                               
#     list_n_people.append(n_people)
    
#     wait = .5 + 10 * random.random()
#     time.sleep(wait)
#     print(f'{url[41:]}, {n_prices}, {n_people}, waited {wait:0.4} sec.')